// Copyright 2017-2021 @reef-chain/extension-dapp authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@reef-chain/extension-dapp', version: '1.0.23' };
